Export PYTHONPATH when sourcing the workspace
ignitionrobotics/ign-math pull request #271
Opened 2021-10-29 08:36 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🦟 Bug fix

## Summary

This PR is related to this issues https://github.com/ignitionrobotics/ign-math/issues/270

When compiling from source and loading the workspace we should be able to setup the PYTHONPATH to allow user to use the Python bindings

There is a discussion in the ign-cmake https://github.com/ignitionrobotics/ign-cmake/issues/185 repository to include this functionality.

One cons about this solution if that if you source the workspace several times you will append the path to the pythonpath each time.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-11-09 02:10 UTC, chapulina commented
@ahcorde , as mentioned in a meeting, let's add documentation instructing users to source the setup file directly when using plain CMake. Also note that this is not needed for debian installations, as we're already installing the scripts in the correct path.

2021-12-30 04:36 UTC, chapulina requested changes

2021-12-30 04:36 UTC, chapulina commented on src/python/setup.sh.in
> +export PYTHONPATH=@CMAKE_INSTALL_PREFIX@/@IGN_PYTHON_INSTALL_PATH@:$PYTHONPATH
This is being set to `install/lib/python/swig`, should it be `install/lib/python`?

2022-01-10 19:36 UTC, ahcorde commented
[This tutorial](https://github.com/ignitionrobotics/ign-math/pull/362/files) explains how to do it. Closing this

2022-01-10 19:36 UTC, closed without merging