Add GaussMarkovProcess pybind11 interface and examples
ignitionrobotics/ign-math pull request #315
Opened 2021-12-17 12:00 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🎉 New feature

## Summary

This PR creates a GaussMarkovProcess Pybind11 interface and adds examples

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2021-12-27 16:56 UTC, chapulina requested changes
Just some comments about the examples

2021-12-27 16:56 UTC, chapulina commented on examples/gauss_markov_process_example.py
> +#     ./gauss_markov_process > plot.data
I think we should tell the user to set `PYTHONPATH` like we do on other examples:

https://github.com/ignitionrobotics/ign-math/blob/1cac6547f141e5f5872d8d2976ebc1ac50633135/examples/angle_example.py#L18-L21

```suggestion
#     python3 gauss_markov_process_example.py > plot.data
```

2021-12-27 16:56 UTC, chapulina commented on examples/gauss_markov_process_example.rb
> +require 'math'
```suggestion
require 'ignition/math'
```

2021-12-27 16:56 UTC, chapulina commented on examples/gauss_markov_process_example.rb
> +#     ./gauss_markov_process > plot.data
Here too we should tell the user to set the env var:

https://github.com/ignitionrobotics/ign-math/blob/1cac6547f141e5f5872d8d2976ebc1ac50633135/examples/angle_example.rb#L18-L21

And

```suggestion
#     ruby gauss_markov_process.rb > plot.data
```

2021-12-28 16:58 UTC, chapulina approved these changes
LGTM, I pushed some tweaks to the examples in b3e1a977691646c046878389445b47279ef77127

2021-12-28 17:26 UTC, merged

2022-03-01 18:30 UTC, osrf-triage commented
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-01-citadel-edifice-fortress/1313/1