Added Temperature pybind11 interface
ignitionrobotics/ign-math pull request #330
Opened 2021-12-24 11:18 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🎉 New feature

## Summary

This PR creates a Temperature Pybind11 interface

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2021-12-27 22:09 UTC, chapulina requested changes

2021-12-27 22:09 UTC, chapulina commented on include/ignition/math/Temperature.hh
> +      public: Temperature operator+(const double _temp) const;
We need to add tests for the new functions so the coverage doesn't drop

2021-12-28 19:48 UTC, chapulina approved these changes
LGTM with happy CI

2021-12-28 19:48 UTC, chapulina commented on src/Temperature.cc
> +  return this->dataPtr->kelvin + _temp;
```suggestion
  return this->dataPtr->kelvin + _temp.Kelvin();
```

I think this may be needed

2021-12-28 22:55 UTC, merged

2022-03-01 18:30 UTC, osrf-triage commented
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-01-citadel-edifice-fortress/1313/1