Added Matrix4 pybind11 interface
ignitionrobotics/ign-math pull request #337
Opened 2021-12-24 12:58 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🎉 New feature

## Summary

This PR creates a Matrix4 Pybind11 interface

Require
 - https://github.com/ignitionrobotics/ign-math/pull/334

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2021-12-27 22:11 UTC, chapulina requested changes
I think we should address this TODO here:

https://github.com/ignitionrobotics/ign-math/blob/f6c26bfc32b730a4a18b735ba492eca53188b186/src/python_pybind11/test/Quaternion_TEST.py#L358-L364

2021-12-27 23:18 UTC, chapulina approved these changes
LGTM with happy CI

2021-12-27 23:18 UTC, chapulina commented on src/python_pybind11/src/_ignition_math_pybind11.cc
> +  ignition::math::python::defineMathMatrix4<float>(m, "Matrix4f");
Ah and this could go up close to `Matrix3`

2021-12-28 00:23 UTC, chapulina requested changes

2021-12-28 00:23 UTC, chapulina commented on src/python_pybind11/src/Matrix4.hh
> +    .def("look_at",
The test failed:

```
   ERROR: test_look_at (__main__.TestMatrix4)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/github/workspace/src/python_pybind11/test/Matrix4_TEST.py", line 450, in test_look_at
      self.assertAlmostEqual(Matrix4d.look_at(-Vector3d.UNIT_X,
  TypeError: look_at(): incompatible function arguments. The following argument types are supported:
      1. (self: ignition.math.Vector3d, arg0: ignition.math.Vector3d, arg1: ignition.math.Vector3d) -> ignition.math.Matrix4d
  
  Invoked with: -1 -0 -0, 0 0 0
```

2021-12-29 00:50 UTC, chapulina approved these changes

2021-12-29 01:09 UTC, merged

2022-03-01 18:30 UTC, osrf-triage commented
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-01-citadel-edifice-fortress/1313/1